---
abstract: 'Easily declare, throw and match exception objects'
author:
  - 'Written by Mark Fowler <mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Err
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Exception::Class: 0
resources:
  homepage: https://github.com/2shortplanks/Err
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/2shortplanks/Err
    web: https://github.com/2shortplanks/Err
version: 0.01
